//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Date
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullNameID
    {
        public FullNameID()
        {
            this.Orders_import = new HashSet<Orders_import>();
            this.Users_import2 = new HashSet<Users_import2>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<Orders_import> Orders_import { get; set; }
        public virtual ICollection<Users_import2> Users_import2 { get; set; }
    }
}
