//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Date
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Clothing_importEntities : DbContext
    {
        public Clothing_importEntities()
            : base("name=Clothing_importEntities")
        {
        }

        public static Clothing_importEntities _context;

        public static Clothing_importEntities GetContext()
        {
            if(_context == null)
            {
                _context = new Clothing_importEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Category { get; set; }
        public DbSet<FullNameID> FullNameID { get; set; }
        public DbSet<Manufacture> Manufacture { get; set; }
        public DbSet<PodCategory> PodCategory { get; set; }
        public DbSet<Product_import> Product_import { get; set; }
        public DbSet<ProductName> ProductName { get; set; }
        public DbSet<RoleID> RoleID { get; set; }
        public DbSet<Size_import2> Size_import2 { get; set; }
        public DbSet<Stock_items_import> Stock_items_import { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Orders_import> Orders_import { get; set; }
        public DbSet<Users_import2> Users_import2 { get; set; }
    }
}
