//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Date
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_import
    {
        public int ID { get; set; }
        public int NumberOrdes { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int FullNameID { get; set; }
        public int CategoryID { get; set; }
        public int ProductNameID { get; set; }
        public int ManufactureID { get; set; }
        public int SizeID { get; set; }
        public int Quantity { get; set; }
        public int UnitPrice { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual FullNameID FullNameID1 { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual Size_import2 Size_import2 { get; set; }
    }
}
