//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Date
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_import
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public int PodCategoryID { get; set; }
        public byte[] Image { get; set; }
        public int ProductNameID { get; set; }
        public int ManufactureID { get; set; }
        public string Description { get; set; }
        public string Sostav { get; set; }
        public int Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacture Manufacture { get; set; }
        public virtual PodCategory PodCategory { get; set; }
        public virtual ProductName ProductName { get; set; }
    }
}
