//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Date
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductName
    {
        public ProductName()
        {
            this.Product_import = new HashSet<Product_import>();
        }
    
        public int ID { get; set; }
        public string ProductName1 { get; set; }
    
        public virtual ICollection<Product_import> Product_import { get; set; }
    }
}
