//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Date
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size_import2
    {
        public Size_import2()
        {
            this.Orders_import = new HashSet<Orders_import>();
        }
    
        public int ID { get; set; }
        public string Size { get; set; }
    
        public virtual ICollection<Orders_import> Orders_import { get; set; }
    }
}
