//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Date
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_items_import
    {
        public int ID { get; set; }
        public int ProductNameID { get; set; }
        public int ManufactureID { get; set; }
        public int SizeID { get; set; }
        public int QuantityForOrders { get; set; }
    
        public virtual Manufacture Manufacture { get; set; }
    }
}
