//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Date
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_import2
    {
        public int ID { get; set; }
        public int FullNameID { get; set; }
        public string Login { get; set; }
        public int RoleID { get; set; }
    
        public virtual FullNameID FullNameID1 { get; set; }
        public virtual RoleID RoleID1 { get; set; }
    }
}
